// ===== METER (from MeterWithSchema.js) =====
import { defineSchema, field, tab, section, FieldTypes, relationship, RelationshipTypes } from '../../../../framework/backend/api/base/SchemaDefinition';

export const meterSchema = defineSchema({
  entityName: 'Meter',
  tableName: 'meter',
  description: 'Meter entity for managing electric, gas, water, and other utility meters',
  formMaxWidth: '770px',

  customListColumns: {},

  formTabs: [
    tab({
      name: 'Meter',
      order: 1,
      minWidth: '400px',
      sections: [
        section({
          name: 'Information',
          order: 1,
          minWidth: '350px',
          fields: [
            field({
              name: 'name',
              order: 1,
              type: FieldTypes.STRING,
              default: '',
              required: true,
              label: 'Meter Name',
              dbField: 'name',
              minLength: 3,
              maxLength: 100,
              placeholder: 'Enter meter name',
              showOn: ['list', 'form'],
              filertable: ['main'],
            }),
            field({
              name: 'serial_number',
              order: 2,
              type: FieldTypes.STRING,
              default: '',
              required: true,
              label: 'Serial Number',
              dbField: 'serial_number',
              maxLength: 200,
              placeholder: 'Enter serial number',
              filertable: ['true'],
              showOn: ['list', 'form'],
              visibleFor: ['physical'],
            }),
            field({
              name: 'device_id',
              order: 3,
              type: FieldTypes.NUMBER,
              default: null,
              required: true,
              label: 'Device',
              dbField: 'device_id',
              min: 1,
              maxLength: 200,
              showOn: ['list', 'form'],
              validate: true,
              validationFields: ['manufacturer', 'model_number'],
              visibleFor: ['physical'],
            }),
            field({
              name: 'location_id',
              order: 4,
              type: FieldTypes.NUMBER,
              default: null,
              required: true,
              label: 'Location',
              dbField: 'location_id',
              min: 1,
              showOn: ['form'],
              validate: true,
              validationFields: ['name'],
            }),
            field({
              name: 'type',
              order: 5,
              type: FieldTypes.SELECT,
              default: 'electric',
              required: true,
              label: 'Meter Type',
              dbField: 'type',
              readOnly: false,
              enumValues: ['electric', 'gas', 'water', 'steam', 'other'],
              enumLabels: {
                electric: 'Electric',
                gas: 'Gas',
                water: 'Water',
                steam: 'Steam',
                other: 'Other',
              },
              showOn: ['form', 'list'],
            }),
          ],
        }),

        section({
          name: 'Network',
          order: 2,
          visibleFor: ['physical'],
          fields: [
            field({
              name: 'ip',
              order: 1,
              type: FieldTypes.STRING,
              default: '',
              required: true,
              label: 'IP Address',
              dbField: 'ip',
              placeholder: '192.168.1.100',
              showOn: ['list', 'form'],
            }),
            field({
              name: 'port',
              order: 2,
              type: FieldTypes.NUMBER,
              default: 47808,
              required: true,
              label: 'Port Number',
              dbField: 'port',
              min: 1,
              max: 65535,
              placeholder: '47808',
              showOn: ['form'],
            }),
          ],
        }),
        section({
          name: 'Status',
          order: 3,
          fields: [
            field({
              name: 'active',
              order: 1,
              type: FieldTypes.BOOLEAN,
              default: true,
              required: true,
              label: 'Active',
              dbField: 'active',
              showOn: ['list', 'form'],
              filertable: ['true'],
            }),
            field({
              name: 'installation_date',
              order: 2,
              type: FieldTypes.DATE,
              default: null,
              required: false,
              label: 'Installation Date',
              dbField: 'installation_date',
              placeholder: 'Select date',
              showOn: ['form'],
            }),
            field({
              name: 'is_virtual',
              order: 3,
              type: FieldTypes.SELECT,
              default: 'physical',
              required: true,
              label: 'Physical/Virtual',
              dbField: 'is_virtual',
              readOnly: true,
              enumValues: ['physical', 'virtual'],
              enumLabels: {
                physical: 'Physical',
                virtual: 'Virtual',
              },
              showOn: ['form', 'list'],
            }),
          ],
        }),
      ],
    }),
    tab({
      name: 'Elements',
      order: 2,
      visibleFor: ['physical'],
      sections: [
        section({
          name: 'Meter Elements',
          order: 1,
          fields: [
            field({
              name: 'elements',
              order: 1,
              type: FieldTypes.OBJECT,
              default: null,
              required: false,
              label: 'Elements',
              dbField: null,
              showOn: ['form'],
            }),
          ],
        }),
      ],
    }),
    tab({
      name: 'Combined Meters',
      order: 2,
      visibleFor: ['virtual'],
      sections: [
        section({
          name: 'Combined Meters',
          order: 1,
          fields: [
            field({
              name: 'elements',
              order: 1,
              type: FieldTypes.OBJECT,
              default: null,
              required: false,
              label: 'Elements',
              dbField: null,
              showOn: ['form'],
            }),
          ],
        }),
      ],
    }),
    tab({
      name: 'Additional Info',
      order: 3,
      sectionOrientation: 'vertical',
      sections: [
        section({
          name: 'notes',
          order: 1,
          minWidth: '500px',
          fields: [
            field({
              name: 'notes',
              order: 1,
              type: FieldTypes.STRING,
              default: '',
              required: false,
              label: 'Notes',
              dbField: 'notes',
              maxLength: 500,
              placeholder: 'Enter notes',
              showOn: ['form'],
            }),
          ],
        }),
        section({
          name: 'Audit',
          order: 2,
          minWidth: '250px',
          fields: [
            field({
              name: 'created_at',
              order: 1,
              type: FieldTypes.DATETIME,
              default: null,
              readOnly: true,
              label: 'Created At',
              dbField: 'created_at',
            }),
            field({
              name: 'updated_at',
              order: 2,
              type: FieldTypes.DATETIME,
              default: null,
              readOnly: true,
              label: 'Updated At',
              dbField: 'updated_at',
            }),
          ],
        }),
      ],
    }),
  ],

  formFields: {
    elements: field({
      type: FieldTypes.OBJECT,
      default: null,
      required: false,
      label: 'Elements',
      dbField: null,
      showOn: ['form'],
    }),
  },

  entityFields: {
    meter_id: field({
      name: 'meter_id',
      type: FieldTypes.NUMBER,
      default: null,
      readOnly: true,
      label: 'ID',
      dbField: 'meter_id',
    }),
    tenant_id: field({
      name: 'tenant_id',
      type: FieldTypes.NUMBER,
      default: 0,
      readOnly: false,
      label: 'Tenant ID',
      dbField: 'tenant_id',
    }),
  },

  validation: {},
});