CREATE TABLE IF NOT EXISTS cost (
  cost_id    SERIAL PRIMARY KEY,
  name       VARCHAR(255) NOT NULL,
  quantity   NUMERIC(18, 6) NOT NULL DEFAULT 0,
  rate       NUMERIC(18, 6) NOT NULL DEFAULT 0,
  active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
